#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__allowed_urls() {
    ynh_replace --match='frame-ancestors [^"]*' --replace="frame-ancestors 'self' $allowed_urls" --file="/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_app_setting_set --key=allowed_urls --value="$allowed_urls"
    ynh_print_info "The nginx config has been edited"
}

# FIXME: this is a yolo fix to remove after merging https://github.com/YunoHost/yunohost/pull/2186
ynh_app_config_apply() {
    _ynh_app_config_apply
    ynh_replace --match='"[Ff]alse"' --replace="false" --file="$install_dir/config/local.json" 
    ynh_replace --match='"[Tt]rue"' --replace="true" --file="$install_dir/config/local.json" 
    ynh_store_file_checksum "$install_dir/config/local.json"
}
#=================================================
ynh_app_config_run "$1"
