#!/bin/bash
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__allowed_urls() {
    ynh_replace --match="frame-ancestors .*" --replace="frame-ancestors 'self' $allowed_urls" --file="/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_app_setting_set --key=allowed_urls --value="$allowed_urls"
    ynh_print_info "The nginx config has been edited"
}
#=================================================
ynh_app_config_run "$1"
