#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers




#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:$app" "$install_dir"
chown "$app:www-data" "$install_dir"
chown "$app:www-data" "$install_dir/documentserver"
chmod go=--- "$install_dir/"{src,bin,config,Data}
chmod o=--- "$install_dir/documentserver"
chmod a-w "$install_dir/documentserver"
chmod 400 "$conf_dir/local.json"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# SETUP RABBIT MQ VHOST
#=================================================
ynh_script_progression "Configuring rabbitmq vhost $app..."

ynh_rabbitmq_setup_vhost

#=================================================
# SETUP REDIS DB
#=================================================
ynh_script_progression "Configuring redis db..."

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app="$app" --key=redis_db --value="$redis_db"
ynh_write_var_in_file --file="$install_dir/config/local.json" --key="database" --value="$redis_db" --after="redis"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression --message="Restoring the PostgreSQL database..." --weight=1

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

for service in "converter" "docservice" "metrics"; do
    ynh_restore "/etc/systemd/system/$app-$service.service"
    systemctl enable "$app-$service.service" --quiet

    yunohost service add "$app-$service" --description="$app $service" --log="/var/log/$app/$service.log"
done
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="$app"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/etc/cron.d/$app"
ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

for service in "converter" "docservice" "metrics"; do
    ynh_systemctl --action=start --service="$app-$service" 
done
ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app"
