#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_safe_rm "/etc/apt/sources.list.d/onlyoffice.list"
ynh_safe_rm "/etc/apt/sources.list.d/nodesource.list"

#=================================================
# CONFIGURE ONLYOFFICE
#=================================================
ynh_script_progression "Upgrading OnlyOffice..."

ynh_backup_if_checksum_is_different "/etc/onlyoffice/documentserver/default.json"

_install_msfonts_deb
_install_onlyoffice_deb

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_backup_if_checksum_is_different "/etc/onlyoffice/documentserver/default.json"

ynh_replace --file="/etc/onlyoffice/documentserver/default.json" \
    --match="\"rejectUnauthorized\": true" \
    --replace="\"rejectUnauthorized\": false"

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "/etc/onlyoffice/documentserver/default.json"

#=================================================
# REGENERATE FONTS
#=================================================
ynh_script_progression "Generating fonts..."

/usr/bin/documentserver-generate-allfonts.sh 2>/dev/null

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R ds:ds "$install_dir"
#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

for service in "ds-converter" "ds-docservice" "ds-metrics"; do
    yunohost service add "$service"
done

#=================================================
# START SERVICES
#=================================================

for service in "ds-converter" "ds-docservice" "ds-metrics"; do
    ynh_systemctl --action=restart --service="$service"
done

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
